### PR TITLE
add test cases for LOG LOG2 LOG10

### PR DESCRIPTION
**Pull request by Fullstop000**
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>

Relate to https://github.com/tikv/tikv/pull/5829
@lonng

### CODE REVIEW

**Comment by Fullstop000** [comment]
Tested in local env

```
019/11/07 10:21:39 Testing [sql/math.sql]...
2019/11/07 10:21:39 Parsing...
2019/11/07 10:21:39 Running...
2019/11/07 10:21:39 Info: run sql
SELECT LOG(3);
2019/11/07 10:21:39 Info: run sql
SELECT LOG(1);
2019/11/07 10:21:39 Info: run sql
SELECT LOG(-3);
2019/11/07 10:21:39 Info: run sql
SELECT LOG(10, 1000);
2019/11/07 10:21:39 Info: run sql
SELECT LOG(1, 1000);
2019/11/07 10:21:39 Info: run sql
SELECT LOG(-1, 10);
2019/11/07 10:21:39 Info: run sql
SELECT LOG2(1);
2019/11/07 10:21:39 Info: run sql
SELECT LOG2(256);
2019/11/07 10:21:39 Info: run sql
SELECT LOG2(-1);
2019/11/07 10:21:39 Info: run sql
SELECT LOG10(1);
2019/11/07 10:21:39 Info: run sql
SELECT LOG10(1000);
2019/11/07 10:21:39 Info: run sql
SELECT LOG10(-1);
2019/11/07 10:21:39 Test summary: Success queries: 12, fail (and ignore) queries: 0 (where there are 0 non-matching queries)
2019/11/07 10:21:39 Test summary: Test case PASS
```

**Comment by lonng** [comment]
@Fullstop000 Thanks for your contribution. The integration tests you added cannot cover the coprocessor RPN functions. We should put them in condition expressions of WHERE clause.
To simplify workflow, @breeswish file a new PR https://github.com/tikv/copr-test/pull/12, which add a bunch of test cases. 
You just need to add the new port functions to `push-down-test/functions.txe` and make your TiKV PR pass the `integration-copr-test`.

**Comment by Fullstop000** [comment]
@lonng Thanks for the reply. The workflow sounds more comprehensive now. Should we update the  https://github.com/tikv/community/blob/master/sig/coprocessor/workflow-zh_CN.md?

**Comment by Fullstop000** [comment]
@lonng @breeswish Could you take a look at CI? I'm not sure what happened according to the CI error message.

**Pull request merged**
