### PR TITLE
randgen: add json test

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Wangweizhen <hawking.rei@gmail.com>

use mariadb/randgen to generate this file. this file contains 1000 sql.

### CODE REVIEW

**Comment by hawkingrei** [comment]
@breeswish PTAL

**Comment by breeswish** [comment]
Good job!

- Is it possible to add JSON fields in the schema?
- The schema should be put in the prepare directory
- Maybe it's better to only generate `SELECT .. WHERE ...` statements

**Comment by hawkingrei** [comment]
Done. Only generate ``` SELECT * FROM JSON_XXX```.

Do i need to push the randgen file to PR. it take many time to complete it.

**Comment by breeswish** [comment]
Good job! According to CI it is finished very quickly: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_integration_copr_test/detail/tidb_ghpr_integration_copr_test/1270/pipeline/

However looks like JSON_LENGTH is commented out, does it contain some implementation mistakes?

**Comment by hawkingrei** [comment]
JSON_LENGTH is commented out because it will cause error ```Unknown signature: JsonLengthSig```.but I will add the JSON_LENGTH with [tikv/5916](https://github.com/tikv/tikv/pull/5916)

**Comment by hawkingrei** [comment]
Have another way that I replace ```JSON_LENGTH``` with ```JSON_DEPTH```. After the JSON_LENGTH merging, I will create a new SQL file with ```JSON_DEPTH``` testing.

**Comment by hawkingrei** [comment]
Adding JSON_LENGTH, then I can use [tikv/5916](https://github.com/tikv/tikv/pull/5916) to test this pr.

**Comment by hawkingrei** [comment]
@breeswish  Add the JSON_LENGTH and tested by [tikv/5916](https://github.com/tikv/tikv/pull/5916).

**Comment by hawkingrei** [comment]
@breeswish  [tikv/5916](https://github.com/tikv/tikv/pull/5916)  has merged. PTAL.

**Comment by breeswish** [comment]
Cool!

**Pull request merged**
